# Linux / WSL bashrc
# Used on Linux VMs and Docker dev containers.

export PS1='\u@\h:\w\$ '

# Shared config
[ -f "$HOME/.config/shell/common.sh" ] && source "$HOME/.config/shell/common.sh"

# Uncomment when oh-my-zsh is installed on this machine (and rename to linux/zshrc):
# export ZSH="$HOME/.oh-my-zsh"
# ZSH_THEME="robbyrussell"
# plugins=(git fzf zoxide lazygit)
# source $ZSH/oh-my-zsh.sh
# eval "$(zoxide init bash)"
